repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.6
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: |
          (?x)^(
            app/modules|
            app/components
          )
        args:
          - --hook-config=--retry-once-with-cleanup=true
      # - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # - id: terraform_checkov
