repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # TODO: Only run Terraform validate against stacks directory due to a known issue in Terraform when using "configuration_aliases" - https://github.com/hashicorp/terraform/issues/28490
  - repo: local
    hooks:
      - id: generate_terraform_providers
        entry: .generate-providers.sh generate
        files: \.tf?$
        language: script
        name: Generate Terraform Providers
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.0
    hooks:
      - id: terraform_validate
        exclude: |
          (?x)^(
            app/modules|
            app/components
          )
  - repo: local
    hooks:
      - id: remove_terraform_providers
        entry: .generate-providers.sh remove
        files: \.tf?$
        language: script
        name: Remove Terraform Providers
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terragrunt_fmt
      - id: checkov
