trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.21.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    validateName: Validate Terraform
    validationSteps:
      - template: steps/terraform_format.yml@templates
      - template: steps/terragrunt_hclfmt.yml@templates
      - template: steps/terraform_tflint.yml@templates
        parameters:
          moduleDirectories:
            - $(Build.Repository.LocalPath)/app/components
            - $(Build.Repository.LocalPath)/app/modules
            - $(Build.Repository.LocalPath)/app/stacks/global
            - $(Build.Repository.LocalPath)/app/stacks/uk-south
            - $(Build.Repository.LocalPath)/app/stacks/uk-west
      - template: steps/run_checkov.yml@templates
      - template: steps/terragrunt_validate_all.yml@templates
        parameters:
          subscriptionId: $(SUBSCRIPTION_ID)
          workingDirectory: $(Build.Repository.LocalPath)/app/stacks
