parameters:
  - name: region
    displayName: Region
    type: string
    default: all
    values:
      - all
      - global
      - uk-south
      - uk-west
  - name: stack
    displayName: Stack
    type: string
    default: all
    values:
      - all
      - common
      - appeals-service
      - applications-service
      - back-office
      - front-door
      - front-door-https
  - name: DRDeployment
    displayName: Disaster Recovery Deployment?
    type: boolean
    default: false

trigger: none

pr: none

resources:
  pipelines:
    - pipeline: infrastructure-environments-ci
      source: infrastructure-environments CI
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.5.5

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        deploymentSteps:
          - script: |
              echo "##vso[build.addbuildtag]stack=${{ parameters.stack }}"
              echo "##vso[build.addbuildtag]region=${{ parameters.region }}"
            displayName: Add stack & region build tag
          - ${{ if eq(parameters.stack, 'all') }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan_all.yml@templates
              parameters:
                artifactName: terraform-config-files
                environmentVariables:
                  ENV: $(ENVIRONMENT)
                  ${{ if eq(parameters.DRDeployment, 'true') }}:
                    DR_DEPLOYMENT: true
                subscriptionId: $(SUBSCRIPTION_ID)
                ${{ if eq(parameters.region, 'all') }}:
                  workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
                ${{ else }}:
                  workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks/${{ parameters.region }}
          - ${{ else }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan.yml@templates
              parameters:
                artifactName: terraform-plan-$(ENVIRONMENT)
                environmentVariables:
                  ENV: $(ENVIRONMENT)
                  ${{ if eq(parameters.DRDeployment, 'true') }}:
                    DR_DEPLOYMENT: true
                region: ${{ parameters.region }}
                stack: ${{ parameters.stack }}
                subscriptionId: $(SUBSCRIPTION_ID)
                workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks/${{ parameters.region }}/${{ parameters.stack }}
        isDeployment: false
      - name: Terraform Apply
        ${{ if eq(parameters.stack, 'all') }}:
          artifact: terraform-config-files
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - ${{ if eq(parameters.stack, 'all') }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_apply_all.yml@templates
              parameters:
                artifactname: terraform-config-files
                environmentVariables:
                  ENV: $(ENVIRONMENT)
                  ${{ if eq(parameters.DRDeployment, 'true') }}:
                    DR_DEPLOYMENT: true
                subscriptionId: $(SUBSCRIPTION_ID)
                ${{ if eq(parameters.region, 'all') }}:
                  workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
                ${{ else }}:
                  workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks/${{ parameters.region }}
          - ${{ else }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_apply.yml@templates
              parameters:
                artifactName: terraform-plan-$(ENVIRONMENT)
                subscriptionId: $(SUBSCRIPTION_ID)
