parameters:
  - name: environments
    displayName: Environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
  - name: stacks
    displayName: Stacks
    type: string
    default: all
    values:
      - all
      - common
      - appeals-service
      - applications-service

trigger: none

pr: none

resources:
  containers:
    - container: terraform-tools
      image: terraform-tools
      endpoint: Container Registry
  pipelines:
    - pipeline: infrastructure-environments-ci
      source: infrastructure-environments CI
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: feature/terragrunt-plan-apply-steps


pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        authType: terraform
        container: terraform-tools
        deploymentSteps:
          - ${{ if eq(parameters.stacks, 'all') }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan_all.yml@templates
              parameters:
                environmentVariables:
                  ENV: $(ENVIRONMENT)
                subscriptionId: $(SUBSCRIPTION_ID)
                workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
          - ${{ else }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan.yml@templates
              parameters:
                artifactName: $(Build.BuildId)_$(ENVIRONMENT)
                environmentVariables:
                  ENV: $(ENVIRONMENT)
                subscriptionId: $(SUBSCRIPTION_ID)
                workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks/${{ parameters.stacks }}
        isDeployment: false
      - name: Terraform Apply
        authType: terraform
        container: terraform-tools
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - ${{ if eq(parameters.stacks, 'all') }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_apply_all.yml@templates
              parameters:
                environmentVariables:
                  ENV: $(ENVIRONMENT)
                subscriptionId: $(SUBSCRIPTION_ID)
                workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
          - ${{ else }}:
            - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_apply.yml@templates
              parameters:
                subscriptionId: $(SUBSCRIPTION_ID)
        ${{ if ne(parameters.stacks, 'all') }}:
          artifact: $(Build.BuildId)_$(ENVIRONMENT)
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
      environments:
        - name: Dev
    ${{ else }}:
      environments: ${{ parameters.environments }}
    project: infrastructure
