parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - test
      - prod

trigger:
  batch: true
  branches:
    include:
    - main

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates

pool:
  vmImage: ubuntu-latest

variables:
  - template: ./variables/${{ parameters.environment }}.yml

stages:
  - stage: Plan
    displayName: Terraform Plan
    jobs:
      - job: Plan
        displayName: Terraform Plan
        steps:
          - script: |
              brew install terragrunt
            displayName: Install dependencies
          - task: AzureCLI@2
            displayName: Azure Authentication
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              azureSubscription: Terraform Dev
              addSpnToEnvironment: true
              inlineScript: |
                echo "##vso[task.setvariable variable=azureClientId]$servicePrincipalId"
                echo "##vso[task.setvariable variable=azureClientSecret]$servicePrincipalKey"
                echo "##vso[task.setvariable variable=azureTenantId]$tenantId"
          - script: |
              terragrunt run-all plan --terragrunt-include-external-dependencies
            displayName: Terragrunt Plan
            env:
              ARM_CLIENT_ID: $(azureClientId)
              ARM_CLIENT_SECRET: $(azureClientSecret)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(azureTenantId)
              ENV: ${{ parameters.environment }}
              TERRAGRUNT_WORKING_DIR: $(Build.Repository.LocalPath)/app/stacks
              TF_INPUT: false

#  - stage: Apply
#      displayName: Terraform Apply
#      jobs:
#        job: Apply
#        displayName: Terraform Apply
#        steps:
