parameters:
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test

trigger: none

pr: none

resources:
  containers:
    - container: terraform-tools
      image: terraform-tools
      endpoint: Container Registry
  pipelines:
    - pipeline: infrastructure-environments-ci
      source: infrastructure-environments CI
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates


pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        authType: terraform
        container: terraform-tools
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan_all.yml@templates
            parameters:
              environmentVariables:
                ENV: $(ENVIRONMENT)
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
        isDeployment: false
      - name: Terraform Apply
        authType: terraform
        container: terraform-tools
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_apply_all.yml@templates
            parameters:
              environmentVariables:
                ENV: $(ENVIRONMENT)
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
      environments:
        - name: Dev
    ${{ else }}:
      environments: ${{ parameters.environments }}
    project: infrastructure
