# run a terraform plan against Dev for each PR

trigger: none

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'core_services_cd'
    environments:
      - name: Dev
    deploymentStages:
      - name: Terraform Plan
        deploymentJobs:
          - name: Plan
            isDeployment: false
            timeoutInMinutes: 30
            steps:
              # Remove front-door and front-door-https stacks from plan when running in non-production environments
              # now covered by individual projects with front door premium
              - script: |
                  rm -rf $(System.DefaultWorkingDirectory)/app/stacks/global/back-office
                  rm -rf $(System.DefaultWorkingDirectory)/app/stacks/global/front-door
                  rm -rf $(System.DefaultWorkingDirectory)/app/stacks/global/front-door-https
                displayName: 'Remove front-door classic stacks from plan'
              - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan_all.yml@templates
                parameters:
                  artifactName: terraform-config-files
                  environmentVariables:
                    ENV: $(ENVIRONMENT)
                  subscriptionId: $(SUBSCRIPTION_ID)
                  workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
