parameters:
  - name: region
    displayName: Region
    type: string
    default: uk-west
    values:
      - uk-west
      - uk-south
  - name: stack
    displayName: Stack
    type: string
    default: appeals-service
    values:
      - appeals-service
      - common
  - name: DRDeployment
    displayName: Disaster Recovery Deployment?
    type: boolean
    default: false

trigger: none

pr: none

resources:
  pipelines:
    - pipeline: infrastructure-environments-ci
      source: infrastructure-environments CI
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    environments:
      - name: Staging
    variableGroupPrefix: 'core_services_cd'
    deploymentStages:
      - name: Terraform Plan
        deploymentJobs:
          - name: Plan
            isDeployment: false
            timeoutInMinutes: 30
            steps:
              - script: |
                  echo "##vso[build.addbuildtag]stack=${{ parameters.stack }}"
                  echo "##vso[build.addbuildtag]region=${{ parameters.region }}"
                displayName: Add stack & region build tag
              - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan.yml@templates
                parameters:
                  artifactName: terraform-plan-$(ENVIRONMENT)
                  environmentVariables:
                    ENV: $(ENVIRONMENT)
                    ${{ if eq(parameters.DRDeployment, 'true') }}:
                      DR_DEPLOYMENT: true
                  region: ${{ parameters.region }}
                  stack: ${{ parameters.stack }}
                  subscriptionId: $(SUBSCRIPTION_ID)
                  workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks/${{ parameters.region }}/${{ parameters.stack }}
      - name: Terraform Apply
        dependsOn:
          - Terraform Plan
        deploymentJobs:
          - name: Apply
            steps:
              - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_apply.yml@templates
                parameters:
                  artifactName: terraform-plan-$(ENVIRONMENT)
                  subscriptionId: $(SUBSCRIPTION_ID)
