parameters:
  - name: environments
    type: object
    default:
      - name: Dev
        variables:
          - template: pipelines/variables/dev.yml@self
      - name: Test
        dependsOn:
          - Dev
        variables:
          - template: pipelines/variables/test.yml@self
      - name: Production
        dependsOn:
          - Test
        variables:
          - template: pipelines/variables/production.yml@self

trigger:
  batch: true
  branches:
    include:
      - main

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: feature/cd-stage-wrapper

pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        azureLogin: true
        deploymentSteps:
          - script: |
              brew install terragrunt
            displayName: Install dependencies
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_plan_all.yml@templates
            parameters:
              environmentVariables:
                ENV: $(ENVIRONMENT)
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
        isDeployment: false
      - name: Terraform Apply
        azureLogin: true
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - script: |
              brew install terragrunt
            displayName: Install dependencies
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terragrunt_apply_all.yml@templates
            parameters:
              environmentVariables:
                ENV: $(ENVIRONMENT)
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(System.DefaultWorkingDirectory)/app/stacks
        isDeployment: true
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
      environments:
        - name: Dev
          variables:
            - template: pipelines/variables/dev.yml@self
    ${{ else }}:
      environments: ${{ parameters.environments }}
    project: infrastructure
