resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates

pool:
  vmImage: ubuntu-latest

variables:
  - template: ./variables/dev.yml

stages:
  - stage: Validate
    displayName: Validate Terraform
    jobs:
      - job: Validate
        displayName: Validate Terraform
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - script: |
              brew install terragrunt
              brew install tflint
              brew install checkov
            displayName: Install dependencies
          - template: steps/terraform_format.yml@templates
          - template: steps/terragrunt_hclfmt.yml@templates
          - template: steps/terraform_tflint.yml@templates
            parameters:
              moduleDirectories:
                - $(Build.Repository.LocalPath)/app/modules
                - $(Build.Repository.LocalPath)/app/stacks
          - template: steps/run_checkov.yml@templates
          - template: steps/terragrunt_validate.yml@templates
            parameters:
              serviceConnection: $(ADO_SERVICE_CONNECTION)
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(Build.Repository.LocalPath)/app/stacks
          - template: steps/git_tagging.yml@templates
            parameters:
              tagPrefix: infrastructure-environments
