trigger:
  branches:
    include:
      - main
  paths:
    include:
    - infrastructure

pr:
  branches:
    include:
      - '*'
  paths:
    include:
    - infrastructure

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.15.1

extends:
  template: pipelines/terraform_checks.yml@templates
  parameters:
    workingDirectory: $(Build.Repository.LocalPath)/infrastructure
    tflintConfigPath: $(Build.Repository.LocalPath)/infrastructure/.tflint.hcl
